# configuração do H7 Database
spring.datasource.url=jdbc:h2:mem:urldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#congiguracao do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
